server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: Manh@1307
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "X2y4L1bbZsl4qjlFpgiR8gXE03uc69Ztg+HsxcuWFP/Y4mBK+QW540AyPpyx6Lb6"